# Zephyr specific cmake changes
find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})

set(CMAKE_CXX_LINK_GROUP_USING_RESCAN_SUPPORTED TRUE CACHE INTERNAL "rescan_cxx_feature")

if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND (CMAKE_SYSTEM_NAME STREQUAL "Linux" OR CMAKE_SYSTEM_NAME STREQUAL "Generic"))
    set(CMAKE_CXX_LINK_GROUP_USING_RESCAN "LINKER:--start-group" "LINKER:--end-group" CACHE INTERNAL "cxx_link_rescan")
    message(STATUS "CMAKE_CXX_LINK_GROUP_USING_RESCAN_SUPPORTED value is ${CMAKE_CXX_LINK_GROUP_USING_RESCAN_SUPPORTED}")
else()
    set(CMAKE_CXX_LINK_GROUP_USING_RESCAN_SUPPORTED FALSE)
endif()
